title = "AKB"
theme = "akb"
languageCode = "en"

pluralizelisttitles = false
sectionPagesMenu = "main"

[params.author]
  name = "Kristoffel Boghaert"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Contact"
  identifier = "contact"
  url = "contact"
  weight = 1

[[menu.main]]
  name = "About AKB"
  identifier = "about"
  url = "about"
  weight = 2

# [[menu.main]]
#   name = "Projects [X]L"
#   identifier = "large"
#   url = "large"
#   weight = 4

# [[menu.main]]
#   name = "Projects M"
#   identifier = "medium"
#   url = "medium"
#   weight = 5

# [[menu.main]]
#   name = "Projects [X]S"
#   identifier = "small"
#   url = "small"
#   weight = 6
