title: architectuur Kristoffel Boghaert
theme: kristoffelboghaert
languageCode: en

pluralizelisttitles: false
sectionPagesMenu: main
paginate: 100

module:
  imports:
    path: github.com/pieterjandesmedt/hugo-theme-kristoffelboghaert
    # path: "../../../hugo-themes/kristoffelboghaert"

taxonomies:
- category: categories
- tag: tags
- series: series

params:
  author: Kristoffel Boghaert
  brand: AKB
  subtitle: architectuur Kristoffel Boghaert

# Header Menu
menu:
  main:
  - name: projects<br/>SACRED
    identifier: sacred
    url: /sacred
    weight: 1

  - name: projects<br/>DWELLING
    identifier: dwelling
    url: /dwelling
    weight: 2

  - name: projects<br/>WORKPLACE & CULTURAL
    identifier: wpc
    url: /wpc
    weight: 3

  - name: About<br/>AKB
    identifier: about
    url: /about/biography
    weight: 4

  - name: Contact
    identifier: contact
    url: /contact
    weight: 5

